// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCvDk8lmRH7ntrUjksdoihAjPC3I2Do0',
    appId: '1:496523960141:web:6a145ff9716772391aa104',
    messagingSenderId: '496523960141',
    projectId: 'recyclepaybitwiz',
    authDomain: 'recyclepaybitwiz.firebaseapp.com',
    storageBucket: 'recyclepaybitwiz.appspot.com',
    measurementId: 'G-DCRP99LP1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPA4714kGa2m7NGj-JAsEOQ4puNfekw2I',
    appId: '1:496523960141:android:6ce09f43e48d5a631aa104',
    messagingSenderId: '496523960141',
    projectId: 'recyclepaybitwiz',
    storageBucket: 'recyclepaybitwiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTxEJxGpYd8xjcYdse2XTb6_Q2U7g4E8',
    appId: '1:496523960141:ios:6cf67f5ddbe6e2461aa104',
    messagingSenderId: '496523960141',
    projectId: 'recyclepaybitwiz',
    storageBucket: 'recyclepaybitwiz.appspot.com',
    iosClientId: '496523960141-3da3gu0rkm8k990a571l4085op18akkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTxEJxGpYd8xjcYdse2XTb6_Q2U7g4E8',
    appId: '1:496523960141:ios:a80dea52d6015f721aa104',
    messagingSenderId: '496523960141',
    projectId: 'recyclepaybitwiz',
    storageBucket: 'recyclepaybitwiz.appspot.com',
    iosClientId: '496523960141-h4mnhfg6gop1nl5hogddqjvo904osqta.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourproject.RunnerTests',
  );
}
